### Create customer with customer-ID
POST {{basePath}}/customer
Content-Type: application/json

{
  "id":"0d26047c-d1fe-42f4-bfde-6fd519d1ba05",
  "status": "STANDARD",
  "name":"Peter",
  "contractType":"ECONOMY",
  "address":{
    "city":"Berlin",
    "street": "Parkstrasse"
  },
  "startDate":"2022-09-09"
}

### Create customer without customer-ID and contractType
POST {{basePath}}/customer
Content-Type: application/json

{
  "status": "STANDARD",
  "name": "Peter",
  "address":{
    "city":"Berlin",
    "street": "Parkstrasse"
  },
  "startDate": "2022-09-01"
}

### Find by customer-ID
GET {{basePath}}/customer/6d787026-86c7-4cfb-b800-4fdda58ed801

### Get unknown customerEntity
GET {{basePath}}/customer/{{$uuid}}

### Get all customers
GET {{basePath}}/customer/